import { repo, type FixtureBuilder } from '../../engine/git/fixtures';
import type { ActInput } from '../../game/missions/schema';
import { CONVENTIONAL_PATTERN } from './shared';

/**
 * The Act 2 boss, "The Dirty Tree" (DESIGN.md section 11). Dex deploys from a clean
 * checkout, so only committed files ship. About 40 files are dirty: a search feature, a
 * component refactor, docs, a version bump, and junk that must never be committed
 * (.env, dist/, node_modules/, a debug log).
 *
 * The twist is the real incident behind the Act 2 Field Mission. The scaffold's
 * .gitignore has `log*`, meant for log files, which also hides src/logger.ts. The app
 * imports it, it works on Kyle's machine, and git never shows it, so it has never been
 * committed. At 1:00 Dex's deploy fails on the missing file.
 */

type Files = Record<string, string>;

function writeAll(builder: FixtureBuilder, files: Files): FixtureBuilder {
  return Object.entries(files).reduce(
    (next, [path, content]) => next.write(path, content),
    builder,
  );
}

/** A tiny TypeScript module, so every generated file looks like real code. */
function moduleFile(name: string, body: string): string {
  return `export function ${name}(): string {\n  return '${body}';\n}\n`;
}

function testFile(subject: string): string {
  return `import { expect, it } from 'vitest';\n\nit('${subject} works', () => {\n  expect(true).toBe(true);\n});\n`;
}

const COMPONENTS = ['Header', 'Footer', 'Button', 'Modal'];
const SEARCH_MODULES = ['index', 'query', 'rank', 'highlight', 'filters'];
const SEARCH_TESTS = ['query', 'rank', 'highlight', 'filters'];

const SCAFFOLD: Files = {
  '.gitignore': '# logs\nlog*\n',
  'package.json': '{\n  "name": "quillwork-web",\n  "version": "1.0.0"\n}\n',
  'README.md': '# Quillwork Web\n\nThe Quillwork AI web app.\n',
  'index.html': '<div id="app"></div>\n<script type="module" src="/src/app.ts"></script>\n',
  'src/app.ts':
    "import { log } from './logger';\nimport { route } from './router';\n\nexport function start(): void {\n  log('starting');\n  route(location.pathname);\n}\n",
  'src/router.ts':
    "export function route(path: string): string {\n  return path === '/' ? 'home' : 'not-found';\n}\n",
  'src/api.ts': "export const BASE_URL = 'https://api.quillwork.ai';\n",
  'src/styles/main.css': 'body {\n  margin: 0;\n}\n',
  'tests/app.test.ts': testFile('app'),
  'tests/router.test.ts': testFile('router'),
  'docs/setup.md': '# Setup\n\n1. npm install\n2. npm run dev\n',
  ...Object.fromEntries(
    COMPONENTS.map((name) => [`src/components/${name}.ts`, moduleFile(name.toLowerCase(), name)]),
  ),
};

/** Edits to files the scaffold already tracks. */
const MODIFIED: Files = {
  'src/app.ts':
    "import { log } from './logger';\nimport { route } from './router';\nimport { mountSearch } from './search';\n\nexport function start(): void {\n  log('starting');\n  mountSearch();\n  route(location.pathname);\n}\n",
  'src/router.ts':
    "export function route(path: string): string {\n  if (path === '/search') return 'search';\n  return path === '/' ? 'home' : 'not-found';\n}\n",
  'src/styles/main.css': 'body {\n  margin: 0;\n  font-family: var(--font-body);\n}\n',
  'tests/app.test.ts': testFile('app with search'),
  'tests/router.test.ts': testFile('search route'),
  'README.md': '# Quillwork Web\n\nThe Quillwork AI web app, now with search.\n',
  'docs/setup.md': '# Setup\n\n1. npm install\n2. Copy .env.example to .env\n3. npm run dev\n',
  'package.json': '{\n  "name": "quillwork-web",\n  "version": "1.1.0"\n}\n',
  ...Object.fromEntries(
    COMPONENTS.map((name) => [
      `src/components/${name}.ts`,
      moduleFile(name.toLowerCase(), `${name} (design tokens)`),
    ]),
  ),
};

/** Real work nobody has committed yet: the search feature and its docs. */
const NEW_WORK: Files = {
  ...Object.fromEntries(
    SEARCH_MODULES.map((name) => [`src/search/${name}.ts`, moduleFile(`search${name}`, name)]),
  ),
  'src/components/SearchBar.ts': moduleFile('searchBar', 'SearchBar'),
  ...Object.fromEntries(
    SEARCH_TESTS.map((name) => [`tests/search/${name}.test.ts`, testFile(`search ${name}`)]),
  ),
  'docs/search.md': '# Search\n\nType in the bar at the top of any page.\n',
  'docs/deploy.md': '# Deploy\n\nDex deploys main from a clean checkout.\n',
  'CHANGELOG.md': '# Changelog\n\n## 1.1.0\n\n- Search\n',
};

/** Build output: regenerated by every build, so it must be ignored, never committed. */
export const DIST_FILES = [
  'dist/index.html',
  ...Array.from({ length: 6 }, (_, index) => `dist/assets/chunk-${String(index + 1)}.js`),
  'dist/assets/index.css',
];

/** Installed dependencies: npm recreates these from package.json. */
export const NODE_MODULES_FILES = [
  'node_modules/.package-lock.json',
  'node_modules/left-pad/index.js',
  'node_modules/left-pad/package.json',
  'node_modules/tiny-emitter/index.js',
  'node_modules/tiny-emitter/package.json',
];

const JUNK: Files = {
  // An obvious placeholder: gitleaks scans this repo, and real-looking keys fail CI.
  '.env': 'API_KEY=dev-only\nDATABASE_URL=postgres://localhost/dev\n',
  'npm-debug.log': 'npm ERR! missing script: deploy\n',
  ...Object.fromEntries(DIST_FILES.map((path) => [path, '/* generated by vite build */\n'])),
  ...Object.fromEntries(NODE_MODULES_FILES.map((path) => [path, '/* installed by npm */\n'])),
};

/** The file hidden by `log*`. Never tracked, imported by src/app.ts. */
export const HIDDEN_FILE = 'src/logger.ts';

/** Every real project file that must be in Dex's checkout, apart from the hidden one. */
export const SOURCE_FILES = [...new Set([...Object.keys(SCAFFOLD), ...Object.keys(NEW_WORK)])];

const setup = writeAll(
  writeAll(
    writeAll(repo().commit('chore: scaffold quillwork web app', SCAFFOLD), MODIFIED),
    NEW_WORK,
  ),
  JUNK,
).write(HIDDEN_FILE, 'export function log(message: string): void {\n  console.info(message);\n}\n');

export const dirtyTree: ActInput['boss'] = {
  id: 'dirty-tree',
  title: 'The Dirty Tree',
  briefing: [
    'Dex deploys from a clean checkout in 3:00. Only committed files ship.',
    'Commit the real work in a few Conventional Commits. Ignore .env, dist/, node_modules/, and logs instead of committing them.',
    'Committing a secret or build output fails the deploy on the spot.',
  ],
  setup: setup.toSpec(),
  timeLimitSeconds: 180,
  objectives: [
    { kind: 'clean' },
    { kind: 'ignored', paths: ['.env'] },
    { kind: 'ignored', paths: DIST_FILES, label: 'dist/ build output is ignored' },
    { kind: 'ignored', paths: NODE_MODULES_FILES, label: 'node_modules/ is ignored' },
    {
      kind: 'tracked',
      paths: SOURCE_FILES,
      label: 'Every source, test, and doc file is committed',
    },
    {
      kind: 'tracked',
      paths: [HIDDEN_FILE],
      label: "Dex's clean checkout has every file the app imports",
    },
    { kind: 'commitCount', min: 4, label: 'At least 3 new commits, one per logical change' },
    {
      kind: 'allMessagesMatch',
      pattern: CONVENTIONAL_PATTERN,
      label: 'Every commit message follows Conventional Commits',
    },
  ],
  failIf: [
    { kind: 'tracked', paths: ['.env'], label: 'A secret (.env) was committed' },
    {
      kind: 'not',
      label: 'Build output or node_modules/ was committed',
      predicate: { kind: 'notTracked', paths: [...DIST_FILES, ...NODE_MODULES_FILES] },
    },
  ],
  twists: [
    {
      atSecondsRemaining: 60,
      message:
        'Dex: "Deploy failed! src/app.ts imports ./logger, but src/logger.ts was never committed. Works on your machine only." Why did git status never show it?',
      // Nothing new appears: the file was on the Workbench all along, hidden by `log*`.
      apply: [],
    },
  ],
};
